services:
  grafana:
    image: ${GRAFANA_IMAGE:-grafana/grafana-enterprise:12.3.2}
    container_name: kubernetes-observability-app-release
    depends_on:
      - prometheus
    ports:
      - '${GRAFANA_PORT:-3010}:3000'
    volumes:
      - type: bind
        source: ./provisioning
        target: /etc/grafana/provisioning
        bind:
          create_host_path: false
    environment:
      GF_LOG_FILTERS: plugin.kubernetes-observability-app:debug
      GF_LOG_LEVEL: info
      GF_INSTALL_PLUGINS: https://github.com/elohmeier/rqlite-datasource/releases/download/v1.1.5/g42-rqlite-datasource-1.1.5.zip;g42-rqlite-datasource,https://github.com/elohmeier/grafana-k8s-app/releases/download/v1.0.3/kubernetes-observability-app-1.0.3.zip;kubernetes-observability-app
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: kubernetes-observability-app,g42-rqlite-datasource
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin

  prometheus:
    image: prom/prometheus:v2.55.1
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=2h
    volumes:
      - type: bind
        source: ./provisioning/prometheus
        target: /etc/prometheus
        bind:
          create_host_path: false
