services:
  grafana:
    image: ${GRAFANA_IMAGE:-grafana/grafana-enterprise:12.3.2}
    container_name: kubernetes-observability-app-release
    depends_on:
      - prometheus
    ports:
      - '${GRAFANA_PORT:-3010}:3000'
    volumes:
      - type: bind
        source: ${PLUGIN_DIR:-./kubernetes-observability-app}
        target: /var/lib/grafana/plugins/kubernetes-observability-app
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ./provisioning
        target: /etc/grafana/provisioning
        read_only: true
        bind:
          create_host_path: false
    environment:
      GF_LOG_FILTERS: plugin.kubernetes-observability-app:debug
      GF_LOG_LEVEL: info
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: kubernetes-observability-app
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin

  prometheus:
    image: prom/prometheus:v2.55.1
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=2h
    volumes:
      - type: bind
        source: ./provisioning/prometheus
        target: /etc/prometheus
        read_only: true
        bind:
          create_host_path: false
