apiVersion: 1

deleteDatasources:
  - name: gdev-prometheus
    orgId: 1
  - name: gdev-prometheus-tech
    orgId: 1
  - name: gdev-elasticsearch
    orgId: 1
  - name: gdev-rqlite
    orgId: 1

datasources:
  - name: gdev-prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: gdev-prometheus-tech
    uid: prometheus-nonprod
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    editable: true

  - name: gdev-elasticsearch
    uid: elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    editable: true

  - name: gdev-rqlite
    uid: infra-metadata
    type: g42-rqlite-datasource
    access: proxy
    url: http://rqlite:4001
    editable: true
